name: "weather_pipeline"
version: "1.0.0"
config-version: 2

profile: "weather_pipeline"

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_pipeline:
    staging:
      +schema: public
    curated:
      +schema: public
      +materialized: view
