weather_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', '') }}"
      dbname: "{{ env_var('DB_NAME', 'MyDB') }}"
      schema: public
      threads: 1
