version: 2

sources:
  - name: public
    schema: public
    tables:
      - name: raw_public_data
        description: "Ingested public weather dataset (e.g. Daily Delhi Climate)"
      - name: raw_fake_data
        description: "Ingested fake weather data from FastAPI"
